services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/calibre # /calibre will work, /calibre/ will not
    volumes:
      - ${DATA_DIR}/config/calibre:/config
      - ${DATA_DIR}/media/books:/data/media/books
    ports:
      - "8181:8181"
      - "8081:8081"
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${DATA_DIR}/config/jackett:/config
      - ${DATA_DIR}/torrents:/data/torrents
    ports:
      - "9117:9117"
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${DATA_DIR}/config/lidarr:/config
      - ${DATA_DIR}:/data
    ports:
      - 8686:8686
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=23006
    volumes:
      - ${DATA_DIR}/config/bittorrent:/config
      - ${DATA_DIR}/torrents:/data/torrents
    ports:
      - "8080:8080"
      - "23006:23006"
      - "23006:23006/udp"
    restart: unless-stopped
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${DATA_DIR}/config/readarr:/config
      - ${DATA_DIR}:/data
    ports:
      - "8787:8787"
    restart: unless-stopped
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${DATA_DIR}/config/plex:/config
      - ${DATA_DIR}/media:/media
    restart: unless-stopped
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - ${DATA_DIR}/torrents:/data/torrents
    restart: unless-stopped
    user: 1000:1000
    environment:
      - TZ=Etc/UTC
      # General config
      - UN_QUIET=false
      - UN_DEBUG=false
      - UN_ERROR_STDERR=false
      - UN_LOG_QUEUES=1m
      - UN_LOG_FILES=10
      - UN_LOG_FILE_MB=10
      - UN_INTERVAL=2m
      - UN_START_DELAY=1m
      - UN_RETRY_DELAY=5m
      - UN_MAX_RETRIES=3
      - UN_PARALLEL=1
      - UN_FILE_MODE=0644
      - UN_DIR_MODE=0755
      - UN_ACTIVITY=false
      # Lidarr Config
      - UN_LIDARR_0_URL=http://lidarr:8686
      - UN_LIDARR_0_API_KEY=9ae154f7a56e4607ae0e4fa60f1e10fe
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    user: 1000:1000
    restart: unless-stopped
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SHARED_DIR=/media/music
      - SLSKD_DOWNLOADS_DIR=/downloads/music
      - SLSKD_INCOMPLETE_DIR=/downloads/incomplete/music
      - SLSKD_SLSK_USERNAME=jokepk
      - SLSKD_SLSK_PASSWORD=123456
    ports:
      - "5030:5030/tcp"
      - "5031:5031/tcp"
      - "50300:50300/tcp"
    volumes:
      - ${DATA_DIR}/config/slskd:/app:rw
      - ${DATA_DIR}/media/music:/media/music:r
      - ${DATA_DIR}/torrents/music:/downloads/music:rw
      - ${DATA_DIR}/torrents/incomplete/music:/downloads/incomplete/music:rw
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    device_cgroup_rules:
      - 'c 10:200 rwm'
    environment:
      - WARP_SLEEP=2
    cap_add:
      - MKNOD
      - AUDIT_WRITE
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ${DATA_DIR}/config/cloudflare-warp:/var/lib/cloudflare-warp
  nginx:
    image: nginx
    volumes:
      - ${DATA_DIR}/config/nginx:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    restart: unless-stopped
